include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # We already enable `parameter_assignments`, so this doesn't provide much value.
    prefer_final_parameters: false
